In [2]:
from mechagogue.serial import unpack_leaf_data

with open("/Users/wangchengrui11/Desktop/SUPER/MARL_Scaled/test_2/report_eval_epoch0000_agent012_trial03_step00.state", "rb") as f:
    leaves = unpack_leaf_data(f.read())

print(f"Number of leaves: {len(leaves)}")

Number of leaves: 8


In [4]:
from dirt.examples.nomnom.train_nomnom import NomNomTrainParams, NomNomReport, NomNomAction
import jax.numpy as jnp
import jax
import jax.tree_util as tu

example_report = [
    NomNomReport(
        actions=NomNomAction(
            forward=jnp.array([0]),
            rotate=jnp.array([0]),
            reproduce=jnp.array([0]),
        ),
        players=jnp.array([True]),
        player_x=jnp.zeros((1, 2), dtype=jnp.int32),
        player_r=jnp.zeros((1,), dtype=jnp.int32),
        player_energy=jnp.zeros((1,), dtype=jnp.float32),
        food_grid=jnp.zeros((5, 5), dtype=bool),
    )
    for _ in range(5)  # or any number ≥ 1 to match the .state file
]

print(jax.tree.structure(example_report))

PyTreeDef([CustomNode(NomNomReport[None], [CustomNode(NomNomAction[None], [*, *, *]), *, *, *, *, *]), CustomNode(NomNomReport[None], [CustomNode(NomNomAction[None], [*, *, *]), *, *, *, *, *]), CustomNode(NomNomReport[None], [CustomNode(NomNomAction[None], [*, *, *]), *, *, *, *, *]), CustomNode(NomNomReport[None], [CustomNode(NomNomAction[None], [*, *, *]), *, *, *, *, *]), CustomNode(NomNomReport[None], [CustomNode(NomNomAction[None], [*, *, *]), *, *, *, *, *])])


In [ ]:
from dirt.examples.nomnom.train_nomnom import NomNomReport
from dirt.envs.nomnom import NomNomAction
import jax.numpy as jnp

example_report = NomNomReport(
    actions=NomNomAction(
        forward=jnp.array([0]),
        rotate=jnp.array([0]),
        reproduce=jnp.array([0]),
    ),
    players=jnp.array([True]),
    player_x=jnp.zeros((1, 2), dtype=jnp.int32),
    player_r=jnp.zeros((1,), dtype=jnp.int32),
    player_energy=jnp.zeros((1,), dtype=jnp.float32),
    food_grid=jnp.zeros((5, 5), dtype=bool),
)


In [13]:
from mechagogue.serial import load_example_data
from dirt.examples.nomnom.train_nomnom import NomNomReport
from dirt.envs.nomnom import NomNomAction
import jax.numpy as jnp

example_report = [NomNomReport(
    actions=NomNomAction(
        forward=jnp.array([0]),
        rotate=jnp.array([0]),
        reproduce=jnp.array([0]),
        ),
    players=jnp.array([True]),
    player_x=jnp.zeros((1, 2), dtype=jnp.int32),
    player_r=jnp.zeros((1,), dtype=jnp.int32),
    player_energy=jnp.zeros((1,), dtype=jnp.float32),
    food_grid=jnp.zeros((5, 5), dtype=bool),
    )
    for _ in range(5)
]

report = load_example_data(example_report, "/Users/wangchengrui11/Desktop/SUPER/MARL_Scaled/test_1/report_eval_epoch0000_agent010_trial02.state")

for i, leaf in enumerate(jax.tree.leaves(report)):
    print(f"Leaf {i}: shape={leaf.shape}, dtype={leaf.dtype}")


Leaf 0: shape=(1,), dtype=int32
Leaf 1: shape=(1,), dtype=int32
Leaf 2: shape=(1,), dtype=int32
Leaf 3: shape=(1,), dtype=bool
Leaf 4: shape=(1, 2), dtype=int32
Leaf 5: shape=(1,), dtype=int32
Leaf 6: shape=(1,), dtype=float32
Leaf 7: shape=(5, 5), dtype=bool
Leaf 8: shape=(1,), dtype=int32
Leaf 9: shape=(1,), dtype=int32
Leaf 10: shape=(1,), dtype=int32
Leaf 11: shape=(1,), dtype=bool
Leaf 12: shape=(1, 2), dtype=int32
Leaf 13: shape=(1,), dtype=int32
Leaf 14: shape=(1,), dtype=float32
Leaf 15: shape=(5, 5), dtype=bool
Leaf 16: shape=(1,), dtype=int32
Leaf 17: shape=(1,), dtype=int32
Leaf 18: shape=(1,), dtype=int32
Leaf 19: shape=(1,), dtype=bool
Leaf 20: shape=(1, 2), dtype=int32
Leaf 21: shape=(1,), dtype=int32
Leaf 22: shape=(1,), dtype=float32
Leaf 23: shape=(5, 5), dtype=bool
Leaf 24: shape=(1,), dtype=int32
Leaf 25: shape=(1,), dtype=int32
Leaf 26: shape=(1,), dtype=int32
Leaf 27: shape=(1,), dtype=bool
Leaf 28: shape=(1, 2), dtype=int32
Leaf 29: shape=(1,), dtype=int32
Leaf 30

In [15]:
from mechagogue.serial import load_example_data
from dirt.examples.nomnom.train_nomnom import NomNomReport
from dirt.envs.nomnom import NomNomAction
import jax.numpy as jnp

example_report = [NomNomReport(
    actions=NomNomAction(forward=jnp.array([0]), rotate=jnp.array([0]), reproduce=jnp.array([0])),
    players=jnp.array([True]),
    player_x=jnp.zeros((1, 2), dtype=jnp.int32),
    player_r=jnp.zeros((1,), dtype=jnp.int32),
    player_energy=jnp.zeros((1,), dtype=jnp.float32),
    food_grid=jnp.zeros((5, 5), dtype=bool),
)]

report_batch = load_example_data(example_report, "/Users/wangchengrui11/Desktop/SUPER/MARL_Scaled/test_2/report_eval_epoch0000_agent004_trial03.state")
report = report_batch[0]  # first step

print("Player positions:", report.player_x)


Player positions: [[[0 2]]

 [[0 2]]

 [[0 2]]

 [[0 2]]

 [[0 2]]]
